TASK 1

In [4]:
import numpy as np
import pandas as pd
import itertools

d1a = pd.read_csv("/content/Lab2 D1A.csv")
d1a.head()

,fid,name,population,county,latitude
0,9001,NEW ENGLAND CHRISTIAN ACADEMY,136,BRISTOL,41.758597
1,9002,SETON ACADEMY FOR GIRLS,57,BRISTOL,41.718407
2,9003,ST ANNA SCHOOL,157,WORCESTER,42.517271
3,9004,SOUTHEAST ALTERNATIVE SCHOOL-MIDDLE SCHOOL,5,PLYMOUTH,41.818210
4,9005,DEVEREUX SCHOOL,123,WORCESTER,42.383875

In [3]:
d1b = pd.read_csv("/content/Lab2 D1B.csv")
d1b.head()

,name,population,county,longitude,level,enrollment,level.1
0,NEW ENGLAND CHRISTIAN ACADEMY,136,BRISTOL,-71.175801,Combined elementary and secondary,120,Combined elementary and secondary
1,SETON ACADEMY FOR GIRLS,57,BRISTOL,-71.147302,Elementary,49,Elementary
2,ST ANNA SCHOOL,157,WORCESTER,-71.751741,Elementary,143,Elementary
3,SOUTHEAST ALTERNATIVE SCHOOL-MIDDLE SCHOOL,5,PLYMOUTH,-71.083393,Elementary,4,Elementary
4,DEVEREUX SCHOOL,123,WORCESTER,-71.968419,Combined elementary and secondary,107,Combined elementary and secondary

In [5]:
d1c = pd.read_csv("/content/Lab2 D1C.csv")
d1c.head()

      county        city  score
0    BRISTOL     SWANSEA     16
1    BRISTOL  FALL RIVER      8
2  WORCESTER  LEOMINSTER     14
3   PLYMOUTH  MIDDLEBORO      1
4  WORCESTER     RUTLAND     16

In [4]:
dup = [ col for col in d1b.columns if col in d1a.columns]
d1b_new = d1b.drop(columns=dup)
combine = pd.concat([d1a,d1b_new],axis=1)
print(combine.head())
print(combine.shape)

    fid                                        name  population     county  \
0  9001               NEW ENGLAND CHRISTIAN ACADEMY         136    BRISTOL
1  9002                     SETON ACADEMY FOR GIRLS          57    BRISTOL
2  9003                              ST ANNA SCHOOL         157  WORCESTER
3  9004  SOUTHEAST ALTERNATIVE SCHOOL-MIDDLE SCHOOL           5   PLYMOUTH
4  9005                             DEVEREUX SCHOOL         123  WORCESTER

    latitude  longitude                              level  enrollment  \
0  41.758597 -71.175801  Combined elementary and secondary         120
1  41.718407 -71.147302                         Elementary          49
2  42.517271 -71.751741                         Elementary         143
3  41.818210 -71.083393                         Elementary           4
4  42.383875 -71.968419  Combined elementary and secondary         107

                             level.1
0  Combined elementary and secondary
1                         Elementary
2                         Elementary
3                         Elementary
4  Combined elementary and secondary
(26983, 9)

In [5]:
print(set(d1a.columns) & set(d1c.columns))

{'county'}

In [6]:
combAC = pd.merge(d1a,d1c,on="county", how="inner")
print(combAC.shape)
print(combAC.columns)

(4221333, 7)
Index(['fid', 'name', 'population', 'county', 'latitude', 'city', 'score'], dtype='object')

TASK 2

Customized you own dataset with the name “customizedData”, add at least one attribute
that should be similar to Lab2 D1A, Lab2 D1B, Lab2 D1C dataset , now add 3 attributes
of Size (small, ,medium, and high), cardinal direction ( North, South, East and West) ,
Timings (full time , part time) and add 2 attributes of your own choice, one attribute should
be categorical and one should be continuous.
B. Merge “customizedData” with Lab2 D1A, Lab2 D1B, Lab2 D1C and produce a resultand
dataset with the name of “modifiedData” and explore/ analyze its number of records and
features before and after merging with the technique of similar records joining.

In [6]:
n = min(len(d1a),len(d1b),len(d1c))

customizedData = pd.DataFrame({
    "name" : d1a["name"].head(n),
    "population" : d1a["population"].head(n),
    "level" : d1b["level"].head(n),
    "county" : d1c["county"].head(n),
    "size" : list(itertools.islice(itertools.cycle(["small","medium","high"]),n)),
    "cardinal direction" : list(itertools.islice(itertools.cycle(["north","south","east","west"]),n)),
    "timings" : list(itertools.islice(itertools.cycle(["fulltime","parttime"]),n)),
    "wages" : np.random.randint(1000,5000,size=n),
    "dept" : list(itertools.islice(itertools.cycle(["HR","manager","clerk"]),n))

})
print(customizedData.head(5))

                                         name  population  \
0               NEW ENGLAND CHRISTIAN ACADEMY         136
1                     SETON ACADEMY FOR GIRLS          57
2                              ST ANNA SCHOOL         157
3  SOUTHEAST ALTERNATIVE SCHOOL-MIDDLE SCHOOL           5
4                             DEVEREUX SCHOOL         123

                               level     county    size cardinal direction  \
0  Combined elementary and secondary    BRISTOL   small              north
1                         Elementary    BRISTOL  medium              south
2                         Elementary  WORCESTER    high               east
3                         Elementary   PLYMOUTH   small               west
4  Combined elementary and secondary  WORCESTER  medium              north

    timings  wages     dept
0  fulltime   1976       HR
1  parttime   1190  manager
2  fulltime   2218    clerk
3  parttime   4823       HR
4  fulltime   3377  manager

Merge “customizedData” with Lab2 D1A, Lab2 D1B, Lab2 D1C and produce a resultand
dataset with the name of “modifiedData” and explore/ analyze its number of records and
features before and after merging with the technique of similar records joining.

In [ ]:
print("Data1 shape:", d1a.shape)
print("Data2 shape:", d1b.shape)
print("Data3 shape:", d1c.shape)
print("CustomizedData shape:", customizedData.shape)


modifiedData = pd.merge(d1a, d1b, on="county", how='inner')
modifiedData = modifiedData.merge(d1c, on="county", how='inner')
modifiedData = modifiedData.merge(customizedData, on="county", how='inner')

print(modifiedData.shape)
modifiedData

Data1 shape: (26983, 5)
Data2 shape: (26983, 7)
Data3 shape: (26983, 3)
CustomizedData shape: (26983, 9)